spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sample?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: sample
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  data:
    redis:
      port: 6379

jwt:
  access-token-expire-time: 300000
  refresh-token-expire-time: 86400000
  secret: secretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKeysecretKey
  authorization:
    header: Authorization
logging:
  level:
    org.hibernate.SQL: debug
server:
  port: 8088
